version: 2

project_name: dothuntcli

changelog:
  disable: true

builds:
  - id: dothuntcli
    main: ./cmd/dothuntcli
    binary: dothuntcli
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    builds:
      - dothuntcli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
